language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-martinlab-static' ]; then cd .. && eval "mv $currentfolder generator-martinlab-static" && cd generator-martinlab-static; fi

